"""Add photo and bio fields to candidates

Revision ID: eea0afa36021
Revises: 
Create Date: 2025-05-16 15:50:26.017569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea0afa36021'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'elections', ['election_id'], ['id'])

    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'elections', ['election_id'], ['id'])
        batch_op.create_foreign_key(None, 'candidates', ['candidate_id'], ['id'])
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bio')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
